// Complete Trilingual Translations for All 28 Detail Pages
// Languages: English (en), Chinese Simplified (zh), Polish (pl)
// Pages: Protection (5), Pensions (5), Health Insurance (3), General Insurance (5), Investments (6)

export type Language = 'en' | 'zh' | 'pl';

export const allDetailTranslations = {
  // ============ PROTECTION PAGES (5) ============
  lifeAssurance: {
    en: { title: "Life Assurance", overview: "Life Assurance provides financial protection for your family in the event of your death. It ensures that your loved ones are financially secure and can maintain their standard of living, pay off debts, and cover essential expenses.", sections: { coverage: [{ heading: "Term Life Assurance", content: "Coverage for a fixed period (10, 20, or 30 years). Ideal for temporary needs like mortgage protection or raising children." }, { heading: "Whole of Life Assurance", content: "Lifelong coverage with guaranteed payout. Provides permanent protection and can build cash value over time." }, { heading: "Decreasing Term Assurance", content: "Coverage amount decreases over time, matching your reducing mortgage balance. Cost-effective mortgage protection." }], exclusions: ["Death from suicide within first 12 months", "Death while engaging in dangerous activities", "Death from undisclosed medical conditions", "Claims with fraudulent information"], features: ["Family protection and financial security", "Mortgage cover to protect your home", "Income replacement for dependents", "Flexible coverage periods and amounts", "Affordable premiums for comprehensive cover"] }, regulatory: "Regulated by the Central Bank of Ireland. All policies comply with Irish insurance regulations and consumer protection requirements.", cta: { title: "Get a Quote", description: "Speak with our expert advisors to find the right coverage for your needs.", button: "Contact Us" } },
    zh: { title: "人寿保险", overview: "人寿保险为您的家人在您身故时提供财务保护。它确保您的亲人在财务上是安全的，并能够维持他们的生活水平、偿还债务和支付基本费用。", sections: { coverage: [{ heading: "定期人寿保险", content: "固定期间的保障（10、20或30年）。非常适合临时需求，如抵押贷款保护或抚养儿童。" }, { heading: "终身人寿保险", content: "终身保障，保证赔付。提供永久保护，并可随时间积累现金价值。" }, { heading: "递减定期保险", content: "保障金额随时间递减，与您不断减少的抵押贷款余额相匹配。经济有效的抵押贷款保护。" }], exclusions: ["首12个月内因自杀导致的死亡", "从事危险活动导致的死亡", "因未披露的医疗状况导致的死亡", "包含欺诈信息的索赔"], features: ["家庭保护和财务安全", "抵押贷款保护以保护您的家", "受抚养人的收入替代", "灵活的保障期限和金额", "全面保护的经济实惠保费"] }, regulatory: "本产品由爱尔兰中央银行监管。所有保单均符合爱尔兰保险法规和消费者保护要求。", cta: { title: "获取报价", description: "与我们的专家顾问交流，为您的需求找到合适的保障。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie na życie", overview: "Ubezpieczenie na życie zapewnia ochronę finansową Twojej rodzinie w przypadku Twojej śmierci. Gwarantuje, że Twoi bliscy będą finansowo bezpieczni i będą mogli utrzymać swój standard życia, spłacić długi i pokryć niezbędne wydatki.", sections: { coverage: [{ heading: "Ubezpieczenie terminowe na życie", content: "Ochrona na ustalony okres (10, 20 lub 30 lat). Idealne do czasowych potrzeb, takich jak ochrona hipoteki lub wychowywanie dzieci." }, { heading: "Ubezpieczenie na całe życie", content: "Ochrona na całe życie z gwarantowaną wypłatą. Zapewnia stałą ochronę i może gromadzić wartość pieniężną w czasie." }, { heading: "Ubezpieczenie terminowe malejące", content: "Kwota ubezpieczenia maleje w czasie, dostosowując się do zmniejszającego się salda hipoteki. Ekonomiczna ochrona hipoteczna." }], exclusions: ["Śmierć z powodu samobójstwa w ciągu pierwszych 12 miesięcy", "Śmierć podczas angażowania się w niebezpieczne działania", "Śmierć z powodu nieujawnionych warunków medycznych", "Roszczenia zawierające fałszywe informacje"], features: ["Ochrona rodziny i bezpieczeństwo finansowe", "Ochrona hipoteczna w celu ochrony domu", "Zastąpienie dochodu dla osób na utrzymaniu", "Elastyczne okresy i kwoty ubezpieczenia", "Przystępne składki za kompleksową ochronę"] }, regulatory: "Produkt ten jest regulowany przez Centralny Bank Irlandii. Wszystkie polisy są zgodne z irlandzkimi przepisami ubezpieczeniowymi i wymogami ochrony konsumentów.", cta: { title: "Uzyskaj wycenę", description: "Porozmawiaj z naszymi doradcami eksperckim, aby znaleźć odpowiednią ochronę dla Twoich potrzeb.", button: "Skontaktuj się z nami" } },
  },

  seriousIllness: {
    en: { title: "Serious Illness Insurance", overview: "Serious Illness Insurance provides a lump sum payment if you are diagnosed with a specified serious illness. This financial cushion helps you focus on recovery without worrying about medical bills, lost income, or household expenses.", sections: { coverage: [{ heading: "Cancer Coverage", content: "Covers most types of cancer diagnosed and confirmed by a specialist. Excludes skin cancers and early-stage cancers." }, { heading: "Heart Attack & Stroke", content: "Covers heart attack and stroke with specific medical criteria. Provides funds for recovery and rehabilitation." }, { heading: "Other Conditions", content: "Includes organ transplant, kidney failure, blindness, deafness, and other specified serious conditions." }], exclusions: ["Pre-existing conditions not disclosed at application", "Illnesses caused by alcohol or drug abuse", "Claims within 30 days of policy start", "Conditions related to high-risk activities"], features: ["Lump sum payment upon diagnosis", "Covers multiple serious conditions", "Quick claim processing", "Flexible coverage amounts", "Peace of mind during recovery"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with all Irish insurance regulations and consumer protection standards.", cta: { title: "Get Protection", description: "Secure your financial future with serious illness coverage.", button: "Contact Us" } },
    zh: { title: "重疾保险", overview: "重疾保险在您被诊断出患有指定重疾时提供一次性赔付。这笔财务保障帮助您专注于康复，而无需担心医疗费用、收入损失或家庭开支。", sections: { coverage: [{ heading: "癌症保障", content: "涵盖由专科医生诊断和确认的大多数癌症类型。不包括皮肤癌和早期癌症。" }, { heading: "心脏病和中风", content: "根据特定医学标准涵盖心脏病和中风。为康复和恢复提供资金。" }, { heading: "其他条件", content: "包括器官移植、肾功能衰竭、失明、失聪和其他指定的重疾。" }], exclusions: ["申请时未披露的既往症", "由酒精或药物滥用引起的疾病", "保单开始后30天内的索赔", "与高风险活动相关的条件"], features: ["诊断后一次性赔付", "涵盖多种重疾", "快速理赔处理", "灵活的保障金额", "康复期间的安心"] }, regulatory: "由爱尔兰中央银行监管。符合所有爱尔兰保险法规和消费者保护标准。", cta: { title: "获得保护", description: "通过重疾保障确保您的财务未来。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie na wypadek poważnej choroby", overview: "Ubezpieczenie na wypadek poważnej choroby zapewnia wypłatę ryczałtu w przypadku zdiagnozowania u Ciebie określonej poważnej choroby. Ta poduszka finansowa pomaga Ci skupić się na zdrowotności bez martwienia się o rachunki medyczne, utratę dochodów lub wydatki domowe.", sections: { coverage: [{ heading: "Pokrycie raka", content: "Obejmuje większość typów raka zdiagnozowanych i potwierdzonych przez specjalistę. Wyklucza raki skóry i raki we wczesnym stadium." }, { heading: "Zawał serca i udar", content: "Obejmuje zawał serca i udar mózgu zgodnie z określonymi kryteriami medycznymi. Zapewnia środki na zdrowienie i rehabilitację." }, { heading: "Inne warunki", content: "Obejmuje przeszczep narządu, niewydolność nerek, ślepotę, głuchotę i inne określone poważne stany." }], exclusions: ["Istniejące wcześniej warunki nieujawnione przy aplikacji", "Choroby spowodowane nadużywaniem alkoholu lub narkotyków", "Roszczenia w ciągu 30 dni od rozpoczęcia polisy", "Warunki związane z działaniami wysokiego ryzyka"], features: ["Wypłata ryczałtu po diagnozie", "Obejmuje wiele poważnych chorób", "Szybkie przetwarzanie roszczeń", "Elastyczne kwoty ubezpieczenia", "Spokój ducha podczas zdrowienia"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna ze wszystkimi irlandzkimi przepisami ubezpieczeniowymi i standardami ochrony konsumentów.", cta: { title: "Uzyskaj ochronę", description: "Zabezpiecz swoją przyszłość finansową dzięki ochronie na wypadek poważnej choroby.", button: "Skontaktuj się z nami" } },
  },

  incomeProtection: {
    en: { title: "Income Protection Insurance", overview: "Income Protection Insurance replaces a percentage of your income if you become unable to work due to illness or injury. This ensures your bills, mortgage, and living expenses continue to be paid while you recover.", sections: { coverage: [{ heading: "Illness Coverage", content: "Covers inability to work due to any illness, from common conditions to serious diseases. Includes mental health conditions." }, { heading: "Injury Coverage", content: "Covers temporary or permanent injuries preventing you from working. Includes accidents and workplace injuries." }, { heading: "Flexible Benefit Period", content: "Choose benefit periods from 12 weeks to age 65. Longer periods provide greater security." }], exclusions: ["Unemployment or job loss", "Voluntary unemployment or career changes", "Pre-existing conditions (depending on policy)", "Claims within first 4 weeks of illness"], features: ["Income replacement up to 60%", "Covers all types of illness and injury", "Flexible deferred periods", "Tax-deductible premiums for self-employed", "Professional support during recovery"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish insurance and consumer protection regulations.", cta: { title: "Protect Your Income", description: "Ensure financial stability during unexpected illness or injury.", button: "Contact Us" } },
    zh: { title: "收入保护保险", overview: "收入保护保险在您因疾病或伤害而无法工作时替代您收入的一定比例。这确保您的账单、抵押贷款和生活费用在您康复期间继续得到支付。", sections: { coverage: [{ heading: "疾病保障", content: "涵盖因任何疾病导致的工作能力丧失，从常见疾病到严重疾病。包括心理健康状况。" }, { heading: "伤害保障", content: "涵盖阻止您工作的临时或永久伤害。包括意外和工作场所伤害。" }, { heading: "灵活福利期", content: "选择从12周到65岁的福利期。更长的期限提供更大的安全保障。" }], exclusions: ["失业或失业", "自愿失业或职业变化", "既往症（取决于保单）", "疾病开始后前4周内的索赔"], features: ["收入替代最高60%", "涵盖所有类型的疾病和伤害", "灵活的延期期限", "自由职业者的税收可扣除保费", "康复期间的专业支持"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰保险和消费者保护法规。", cta: { title: "保护您的收入", description: "在意外疾病或伤害期间确保财务稳定。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie ochrony dochodów", overview: "Ubezpieczenie ochrony dochodów zastępuje procent Twoich dochodów, jeśli staniesz się niezdolny do pracy z powodu choroby lub urazu. To gwarantuje, że Twoje rachunki, hipoteka i wydatki na życie będą nadal opłacane podczas Twojego zdrowienia.", sections: { coverage: [{ heading: "Pokrycie choroby", content: "Obejmuje niezdolność do pracy z powodu jakiejkolwiek choroby, od powszechnych schorzeń po poważne choroby. Obejmuje zaburzenia zdrowia psychicznego." }, { heading: "Pokrycie urazu", content: "Obejmuje tymczasowe lub trwałe urazy uniemożliwiające pracę. Obejmuje wypadki i urazy w miejscu pracy." }, { heading: "Elastyczny okres świadczeń", content: "Wybierz okresy świadczeń od 12 tygodni do wieku 65 lat. Dłuższe okresy zapewniają większe bezpieczeństwo." }], exclusions: ["Bezrobocie lub utrata pracy", "Dobrowolne bezrobocie lub zmiany kariery", "Istniejące wcześniej warunki (w zależności od polisy)", "Roszczenia w ciągu pierwszych 4 tygodni choroby"], features: ["Zastąpienie dochodu do 60%", "Obejmuje wszystkie rodzaje chorób i urazów", "Elastyczne okresy odroczenia", "Podatnie odliczalne składki dla osób samozatrudnionych", "Profesjonalne wsparcie podczas zdrowienia"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami ubezpieczeniowymi i ochrony konsumentów.", cta: { title: "Chroń swój dochód", description: "Zapewnij stabilność finansową w przypadku nieoczekiwanej choroby lub urazu.", button: "Skontaktuj się z nami" } },
  },

  // ============ PENSIONS PAGES (5) ============
  prsa: {
    en: { title: "Personal Retirement Savings Account (PRSA)", overview: "A PRSA is a flexible, portable pension account designed for employees and self-employed individuals. It offers simplicity, portability, and tax relief on contributions, making it an ideal retirement savings solution.", sections: { keyAspects: [{ heading: "Flexibility", content: "Contribute as much or as little as you wish, with no mandatory contribution requirements." }, { heading: "Portability", content: "Your PRSA moves with you between employers and jobs. No penalties for changing providers." }, { heading: "Investment Options", content: "Choose from a wide range of investment funds based on your risk tolerance." }, { heading: "Accessibility", content: "Access your PRSA from age 60. Take a tax-free lump sum (up to 25%) and purchase an annuity or access through an ARF." }], taxBenefits: [{ heading: "Tax Relief on Contributions", content: "Receive tax relief at your marginal rate of taxation (up to 40% for higher earners)." }, { heading: "Tax-Free Growth", content: "Your investment growth within the PRSA is tax-free." }, { heading: "Tax-Free Lump Sum", content: "At retirement, take up to 25% of your PRSA fund as a tax-free lump sum." }, { heading: "Employer Contributions", content: "If your employer contributes, these are tax-deductible for the employer." }] }, regulatory: "Regulated by the Pensions Authority of Ireland. All PRSAs comply with Irish pension regulations and consumer protection requirements.", cta: { title: "Open a PRSA", description: "Start your retirement savings journey with a flexible PRSA.", button: "Contact Us" } },
    zh: { title: "个人退休储蓄账户(PRSA)", overview: "PRSA是为员工和自雇人士设计的灵活、便携式养老金账户。它提供简单性、便携性和缴款税收减免，是理想的退休储蓄解决方案。", sections: { keyAspects: [{ heading: "灵活性", content: "随意贡献，没有强制性贡献要求。" }, { heading: "便携性", content: "您的PRSA随您在雇主和工作之间移动。更改提供商没有处罚。" }, { heading: "投资选项", content: "根据您的风险承受能力从广泛的投资基金中选择。" }, { heading: "可访问性", content: "从60岁开始访问您的PRSA。提取高达25%的免税一次性款项并购买年金或通过ARF访问。" }], taxBenefits: [{ heading: "缴款税收减免", content: "以您的边际税率获得税收减免（高收入者最高40%）。" }, { heading: "免税增长", content: "您的PRSA内的投资增长是免税的。" }, { heading: "免税一次性款项", content: "退休时，最多可以25%作为免税一次性款项。" }, { heading: "雇主缴款", content: "如果您的雇主缴款，这些对雇主是税收可扣除的。" }] }, regulatory: "由爱尔兰养老金局监管。所有PRSA均符合爱尔兰养老金法规和消费者保护要求。", cta: { title: "开设PRSA", description: "通过灵活的PRSA开始您的退休储蓄之旅。", button: "联系我们" } },
    pl: { title: "Osobisty Rachunek Oszczędności Emerytalnej (PRSA)", overview: "PRSA to elastyczne, przenośne konto emerytalne zaprojektowane dla pracowników i osób samozatrudnionych. Oferuje prostotę, przenośność i ulgę podatkową na składki, co czyni go idealnym rozwiązaniem do oszczędzania na emeryturę.", sections: { keyAspects: [{ heading: "Elastyczność", content: "Możesz wnosić tyle, ile chcesz, bez obowiązkowych wymogów dotyczących wkładów." }, { heading: "Przenośność", content: "Twoje PRSA porusza się z Tobą między pracodawcami i pracami. Brak kar za zmianę dostawcy." }, { heading: "Opcje inwestycyjne", content: "Wybieraj z szerokiej gamy funduszy inwestycyjnych w oparciu o Twoją tolerancję ryzyka." }, { heading: "Dostępność", content: "Uzyskaj dostęp do PRSA od wieku 60 lat. Weź do 25% wolną od podatku ryczałtową sumę i kup rentę lub uzyskaj dostęp poprzez ARF." }], taxBenefits: [{ heading: "Ulga podatkowa na składki", content: "Otrzymujesz ulgę podatkową w wysokości Twojej krańcowej stawki podatkowej (do 40% dla wyższych zarobków)." }, { heading: "Wzrost wolny od podatku", content: "Wzrost inwestycji w ramach PRSA jest wolny od podatku." }, { heading: "Ryczałtowa suma wolna od podatku", content: "Na emeryturze możesz wziąć do 25% funduszu PRSA jako ryczałtową sumę wolną od podatku." }, { heading: "Składki pracodawcy", content: "Jeśli Twój pracodawca wpłaca, te składki są podatnie odliczalne dla pracodawcy." }] }, regulatory: "Regulowana przez Urząd Emerytalny Irlandii. Wszystkie PRSA są zgodne z irlandzkimi przepisami emerytalnymi i wymogami ochrony konsumentów.", cta: { title: "Otwórz PRSA", description: "Zacznij swoją podrót oszczędzania na emeryturę z elastycznym PRSA.", button: "Skontaktuj się z nami" } },
  },

  avc: {
    en: { title: "Additional Voluntary Contributions (AVC)", overview: "AVCs allow you to make additional contributions to your workplace pension scheme beyond the mandatory employer contributions. This is an excellent way to boost your retirement savings and increase your pension income.", sections: { keyAspects: [{ heading: "Flexible Contributions", content: "Contribute as much as you wish, up to annual limits set by Revenue." }, { heading: "Tax Relief", content: "Receive tax relief on all contributions at your marginal rate." }, { heading: "Investment Control", content: "Choose how your contributions are invested from available fund options." }, { heading: "Portability", content: "Your AVC can move with you between employers. No penalties for transferring." }], taxBenefits: [{ heading: "Immediate Tax Relief", content: "Get tax relief at source on all AVC contributions." }, { heading: "Tax-Free Growth", content: "Investment growth within the AVC is tax-free." }, { heading: "Tax-Free Lump Sum", content: "At retirement, take up to 25% as a tax-free lump sum." }] }, regulatory: "Regulated by the Pensions Authority of Ireland. All AVCs comply with Irish pension regulations.", cta: { title: "Boost Your Pension", description: "Increase your retirement savings with an AVC.", button: "Contact Us" } },
    zh: { title: "额外自愿缴款(AVC)", overview: "AVC允许您在工作场所养老金计划中进行额外缴款，超过强制性雇主缴款。这是增加退休储蓄和增加养老金收入的绝佳方式。", sections: { keyAspects: [{ heading: "灵活缴款", content: "随意缴款，最高为收入部门设定的年度限额。" }, { heading: "税收减免", content: "以您的边际税率获得所有缴款的税收减免。" }, { heading: "投资控制", content: "从可用的基金选项中选择如何投资您的缴款。" }, { heading: "便携性", content: "您的AVC可以随您在雇主之间移动。转移没有处罚。" }], taxBenefits: [{ heading: "即时税收减免", content: "在源头获得所有AVC缴款的税收减免。" }, { heading: "免税增长", content: "AVC内的投资增长是免税的。" }, { heading: "免税一次性款项", content: "退休时，最多可以25%作为免税一次性款项。" }] }, regulatory: "由爱尔兰养老金局监管。所有AVC均符合爱尔兰养老金法规。", cta: { title: "提高您的养老金", description: "通过AVC增加您的退休储蓄。", button: "联系我们" } },
    pl: { title: "Dodatkowe Dobrowolne Składki (AVC)", overview: "AVC pozwala na wnosienie dodatkowych składek do pracowniczego programu emerytalnego poza obowiązkowe składki pracodawcy. To doskonały sposób na zwiększenie oszczędności emerytalnych i zwiększenie dochodu emerytalnego.", sections: { keyAspects: [{ heading: "Elastyczne składki", content: "Wnosi tyle, ile chcesz, do rocznych limitów ustalonych przez Urząd Skarbowy." }, { heading: "Ulga podatkowa", content: "Otrzymaj ulgę podatkową na wszystkie składki w wysokości Twojej krańcowej stawki." }, { heading: "Kontrola inwestycji", content: "Wybierz sposób inwestowania swoich składek z dostępnych opcji funduszy." }, { heading: "Przenośność", content: "Twoje AVC może poruszać się z Tobą między pracodawcami. Brak kar za przeniesienie." }], taxBenefits: [{ heading: "Natychmiastowa ulga podatkowa", content: "Uzyskaj ulgę podatkową u źródła na wszystkie składki AVC." }, { heading: "Wzrost wolny od podatku", content: "Wzrost inwestycji w ramach AVC jest wolny od podatku." }, { heading: "Ryczałtowa suma wolna od podatku", content: "Na emeryturze weź do 25% jako ryczałtową sumę wolną od podatku." }] }, regulatory: "Regulowana przez Urząd Emerytalny Irlandii. Wszystkie AVC są zgodne z irlandzkimi przepisami emerytalnymi.", cta: { title: "Zwiększ swoją emeryturę", description: "Zwiększ swoje oszczędności emerytalne dzięki AVC.", button: "Skontaktuj się z nami" } },
  },

  occupationalPension: {
    en: { title: "Occupational Pension Schemes", overview: "Occupational pensions are employer-sponsored retirement schemes that provide retirement income based on your salary and years of service. They offer security, employer contributions, and professional management.", sections: { keyAspects: [{ heading: "Employer Contributions", content: "Your employer contributes to your pension, often matching or exceeding your contributions." }, { heading: "Defined Benefits", content: "Many schemes offer guaranteed retirement income based on your final salary." }, { heading: "Professional Management", content: "Your pension is professionally managed by experienced fund managers." }, { heading: "Security", content: "Protected by the Pensions Authority and covered by pension protection funds." }], taxBenefits: [{ heading: "Tax-Free Employer Contributions", content: "Employer contributions are not treated as taxable income." }, { heading: "Tax Relief on Employee Contributions", content: "Your contributions receive tax relief at your marginal rate." }] }, regulatory: "Regulated by the Pensions Authority of Ireland. All schemes comply with Irish pension regulations.", cta: { title: "Learn About Your Scheme", description: "Understand your occupational pension benefits.", button: "Contact Us" } },
    zh: { title: "职业养老金计划", overview: "职业养老金是由雇主赞助的退休计划，根据您的工资和服务年限提供退休收入。它们提供安全性、雇主缴款和专业管理。", sections: { keyAspects: [{ heading: "雇主缴款", content: "您的雇主向您的养老金缴款，通常与您的缴款相匹配或超过。" }, { heading: "确定的福利", content: "许多计划根据您的最终工资提供保证的退休收入。" }, { heading: "专业管理", content: "您的养老金由经验丰富的基金经理专业管理。" }, { heading: "安全性", content: "受养老金局保护，由养老金保护基金承保。" }], taxBenefits: [{ heading: "免税雇主缴款", content: "雇主缴款不被视为应税收入。" }, { heading: "员工缴款税收减免", content: "您的缴款以您的边际税率获得税收减免。" }] }, regulatory: "由爱尔兰养老金局监管。所有计划均符合爱尔兰养老金法规。", cta: { title: "了解您的计划", description: "了解您的职业养老金福利。", button: "联系我们" } },
    pl: { title: "Pracownicze Programy Emerytalne", overview: "Emerytury zawodowe to sponsorowane przez pracodawcę programy emerytalne, które zapewniają dochód emerytalny na podstawie Twojej pensji i lat pracy. Oferują bezpieczeństwo, składki pracodawcy i profesjonalne zarządzanie.", sections: { keyAspects: [{ heading: "Składki pracodawcy", content: "Twój pracodawca wpłaca na Twoją emeryturę, często dopasowując lub przekraczając Twoje składki." }, { heading: "Określone świadczenia", content: "Wiele programów oferuje gwarantowany dochód emerytalny na podstawie Twojej ostatecznej pensji." }, { heading: "Profesjonalne zarządzanie", content: "Twoja emerytura jest profesjonalnie zarządzana przez doświadczonych menedżerów funduszy." }, { heading: "Bezpieczeństwo", content: "Chroniona przez Urząd Emerytalny i objęta funduszami ochrony emerytalnej." }], taxBenefits: [{ heading: "Wolne od podatku składki pracodawcy", content: "Składki pracodawcy nie są traktowane jako dochód podlegający opodatkowaniu." }, { heading: "Ulga podatkowa na składki pracownika", content: "Twoje składki otrzymują ulgę podatkową w wysokości Twojej krańcowej stawki." }] }, regulatory: "Regulowana przez Urząd Emerytalny Irlandii. Wszystkie programy są zgodne z irlandzkimi przepisami emerytalnymi.", cta: { title: "Dowiedz się o swoim programie", description: "Zrozum korzyści swojej emerytury zawodowej.", button: "Skontaktuj się z nami" } },
  },

  arf: {
    en: { title: "Approved Retirement Fund (ARF)", overview: "An ARF is a flexible retirement savings vehicle that allows you to draw income at your own pace after retirement. It provides flexibility, investment control, and can be passed to your heirs.", sections: { keyAspects: [{ heading: "Flexible Withdrawals", content: "Draw income at your own pace. No mandatory withdrawal amounts." }, { heading: "Investment Control", content: "Choose how your funds are invested from a wide range of options." }, { heading: "Inheritance", content: "Your ARF can be passed to your heirs, providing financial security for your family." }, { heading: "Tax Efficiency", content: "Manage your tax liability through flexible withdrawal planning." }], taxBenefits: [{ heading: "Tax-Free Growth", content: "Investment growth within the ARF is tax-free." }, { heading: "Flexible Tax Planning", content: "Draw income strategically to manage your tax position." }, { heading: "Inheritance Tax Efficiency", content: "Pass your ARF to heirs with tax efficiency." }] }, regulatory: "Regulated by the Pensions Authority of Ireland. All ARFs comply with Irish pension regulations.", cta: { title: "Explore ARF Options", description: "Discover how an ARF can provide retirement flexibility.", button: "Contact Us" } },
    zh: { title: "批准的退休基金(ARF)", overview: "ARF是一种灵活的退休储蓄工具，允许您在退休后按自己的步调提取收入。它提供灵活性、投资控制，并可以传递给您的继承人。", sections: { keyAspects: [{ heading: "灵活提取", content: "按您自己的步调提取收入。没有强制性提取金额。" }, { heading: "投资控制", content: "从广泛的选项中选择如何投资您的资金。" }, { heading: "继承", content: "您的ARF可以传递给您的继承人，为您的家人提供财务安全。" }, { heading: "税收效率", content: "通过灵活的提取规划管理您的税收责任。" }], taxBenefits: [{ heading: "免税增长", content: "ARF内的投资增长是免税的。" }, { heading: "灵活的税收规划", content: "战略性地提取收入以管理您的税收状况。" }, { heading: "继承税收效率", content: "以税收效率将您的ARF传递给继承人。" }] }, regulatory: "由爱尔兰养老金局监管。所有ARF均符合爱尔兰养老金法规。", cta: { title: "探索ARF选项", description: "发现ARF如何提供退休灵活性。", button: "联系我们" } },
    pl: { title: "Zatwierdzony Fundusz Emerytalny (ARF)", overview: "ARF to elastyczne narzędzie oszczędzania na emeryturę, które pozwala na pobieranie dochodów we własnym tempie po przejściu na emeryturę. Zapewnia elastyczność, kontrolę inwestycji i może być przekazane Twoim spadkobiercom.", sections: { keyAspects: [{ heading: "Elastyczne wypłaty", content: "Pobieraj dochód we własnym tempie. Brak obowiązkowych kwot wypłat." }, { heading: "Kontrola inwestycji", content: "Wybierz sposób inwestowania swoich środków z szerokiej gamy opcji." }, { heading: "Dziedziczenie", content: "Twoje ARF może być przekazane Twoim spadkobiercom, zapewniając bezpieczeństwo finansowe Twojej rodzinie." }, { heading: "Efektywność podatkowa", content: "Zarządzaj swoją odpowiedzialnością podatkową poprzez elastyczne planowanie wypłat." }], taxBenefits: [{ heading: "Wzrost wolny od podatku", content: "Wzrost inwestycji w ramach ARF jest wolny od podatku." }, { heading: "Elastyczne planowanie podatkowe", content: "Strategicznie pobieraj dochód, aby zarządzać swoją pozycją podatkową." }, { heading: "Efektywność podatku od spadków", content: "Przekaż swoje ARF spadkobiercom z efektywnością podatkową." }] }, regulatory: "Regulowana przez Urząd Emerytalny Irlandii. Wszystkie ARF są zgodne z irlandzkimi przepisami emerytalnymi.", cta: { title: "Poznaj opcje ARF", description: "Odkryj, jak ARF może zapewnić elastyczność emerytury.", button: "Skontaktuj się z nami" } },
  },

  // ============ HEALTH INSURANCE PAGES (3) ============
  individualHealth: {
    en: { title: "Individual Health Insurance", overview: "Individual health insurance provides comprehensive medical coverage for you and your immediate family. It ensures access to private healthcare services, reducing waiting times and providing choice of healthcare providers.", sections: { coverage: [{ heading: "Hospital Coverage", content: "Covers hospital accommodation, surgical procedures, and emergency care." }, { heading: "Outpatient Services", content: "Includes consultations, diagnostic tests, and specialist referrals." }, { heading: "Prescription Drugs", content: "Coverage for prescribed medications and treatments." }], exclusions: ["Cosmetic procedures", "Experimental treatments", "Conditions related to alcohol or drug abuse", "Pre-existing conditions (depending on policy)"], features: ["No waiting lists", "Choice of hospitals and consultants", "24/7 emergency support", "Worldwide coverage options", "Family coverage available"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish insurance regulations and consumer protection standards.", cta: { title: "Get a Quote", description: "Obtain personalized coverage for your healthcare needs.", button: "Contact Us" } },
    zh: { title: "个人健康保险", overview: "个人健康保险为您和您的直系家庭成员提供全面的医疗保障。它确保获得私人医疗服务，减少等待时间并提供医疗提供者的选择。", sections: { coverage: [{ heading: "医院保障", content: "涵盖医院住宿、手术程序和紧急护理。" }, { heading: "门诊服务", content: "包括咨询、诊断测试和专科医生转诊。" }, { heading: "处方药", content: "处方药和治疗的保障。" }], exclusions: ["美容手术", "实验性治疗", "与酒精或药物滥用相关的状况", "既往症（取决于保单）"], features: ["无等待列表", "医院和顾问的选择", "24/7紧急支持", "全球保障选项", "家庭保障可用"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰保险法规和消费者保护标准。", cta: { title: "获取报价", description: "为您的医疗保健需求获得个性化保障。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Zdrowotne Indywidualne", overview: "Ubezpieczenie zdrowotne indywidualne zapewnia kompleksowe ubezpieczenie medyczne dla Ciebie i Twojej bezpośredniej rodziny. Gwarantuje dostęp do prywatnych usług opieki zdrowotnej, skracając czasy oczekiwania i zapewniając wybór dostawców opieki zdrowotnej.", sections: { coverage: [{ heading: "Pokrycie szpitalne", content: "Obejmuje zakwaterowanie szpitalne, procedury chirurgiczne i opiekę ratunkową." }, { heading: "Usługi ambulatoryjne", content: "Obejmuje konsultacje, testy diagnostyczne i skierowania do specjalistów." }, { heading: "Leki na receptę", content: "Pokrycie leków na receptę i leczenia." }], exclusions: ["Procedury kosmetyczne", "Leczenie eksperymentalne", "Warunki związane z alkoholem lub narkotykami", "Istniejące wcześniej warunki (w zależności od polisy)"], features: ["Brak list oczekujących", "Wybór szpitali i konsultantów", "Wsparcie awaryjne 24/7", "Opcje pokrycia na całym świecie", "Dostępne pokrycie rodzinne"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami ubezpieczeniowymi i standardami ochrony konsumentów.", cta: { title: "Uzyskaj wycenę", description: "Uzyskaj spersonalizowane pokrycie dla Twoich potrzeb zdrowotnych.", button: "Skontaktuj się z nami" } },
  },

  familyHealth: {
    en: { title: "Family Health Insurance", overview: "Family health insurance extends coverage to your entire family, providing comprehensive medical protection for all members. It offers better value than individual policies and ensures everyone has access to quality healthcare.", sections: { coverage: [{ heading: "Comprehensive Coverage", content: "Covers all family members from children to adults." }, { heading: "Preventive Care", content: "Includes wellness programs, vaccinations, and health screenings." }, { heading: "Maternity Coverage", content: "Covers pregnancy, childbirth, and postnatal care." }], exclusions: ["Cosmetic procedures", "Experimental treatments", "Conditions from accidents while under influence", "Pre-existing conditions (depending on policy)"], features: ["Better value for families", "Covers spouse and children", "Wellness programs included", "Flexible coverage options", "Family health records management"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish insurance and consumer protection regulations.", cta: { title: "Protect Your Family", description: "Ensure your entire family has access to quality healthcare.", button: "Contact Us" } },
    zh: { title: "家庭健康保险", overview: "家庭健康保险将保障范围扩展到您的整个家庭，为所有成员提供全面的医疗保护。与个人保单相比，它提供更好的价值，并确保每个人都能获得优质医疗。", sections: { coverage: [{ heading: "全面保障", content: "涵盖从儿童到成人的所有家庭成员。" }, { heading: "预防护理", content: "包括健康计划、疫苗接种和健康筛查。" }, { heading: "产妇保障", content: "涵盖怀孕、分娩和产后护理。" }], exclusions: ["美容手术", "实验性治疗", "因在影响下的事故造成的状况", "既往症（取决于保单）"], features: ["为家庭提供更好的价值", "涵盖配偶和子女", "包括健康计划", "灵活的保障选项", "家庭健康记录管理"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰保险和消费者保护法规。", cta: { title: "保护您的家庭", description: "确保您的整个家庭都能获得优质医疗。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Zdrowotne Rodzinne", overview: "Ubezpieczenie zdrowotne rodzinne rozszerza pokrycie na całą Twoją rodzinę, zapewniając kompleksową ochronę medyczną dla wszystkich członków. Oferuje lepszą wartość niż polisy indywidualne i zapewnia, że każdy ma dostęp do wysokiej jakości opieki zdrowotnej.", sections: { coverage: [{ heading: "Kompleksowe pokrycie", content: "Obejmuje wszystkich członków rodziny od dzieci do dorosłych." }, { heading: "Opieka profilaktyczna", content: "Obejmuje programy wellness, szczepienia i badania zdrowotne." }, { heading: "Pokrycie macierzyńskie", content: "Obejmuje ciążę, poród i opiekę poporodową." }], exclusions: ["Procedury kosmetyczne", "Leczenie eksperymentalne", "Warunki z wypadków pod wpływem", "Istniejące wcześniej warunki (w zależności od polisy)"], features: ["Lepsza wartość dla rodzin", "Obejmuje małżonka i dzieci", "Programy wellness w zestawie", "Elastyczne opcje pokrycia", "Zarządzanie rejestrami zdrowia rodziny"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami ubezpieczeniowymi i ochrony konsumentów.", cta: { title: "Chroń swoją rodzinę", description: "Zapewnij całej rodzinie dostęp do wysokiej jakości opieki zdrowotnej.", button: "Skontaktuj się z nami" } },
  },

  corporateHealth: {
    en: { title: "Corporate Health Insurance", overview: "Corporate health insurance provides group coverage for employees, offering comprehensive medical benefits at competitive rates. It enhances employee satisfaction, improves retention, and demonstrates corporate responsibility.", sections: { coverage: [{ heading: "Employee Coverage", content: "Comprehensive medical coverage for all eligible employees." }, { heading: "Dependents", content: "Optional coverage for spouses and children." }, { heading: "Wellness Programs", content: "Includes health screenings, fitness programs, and mental health support." }], exclusions: ["Cosmetic procedures", "Experimental treatments", "Conditions from workplace negligence", "Pre-existing conditions (depending on policy)"], features: ["Group discounts", "Flexible plan options", "Employee wellness programs", "Easy administration", "Competitive group rates"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish employment and insurance regulations.", cta: { title: "Employer Solutions", description: "Provide your employees with comprehensive health coverage.", button: "Contact Us" } },
    zh: { title: "企业健康保险", overview: "企业健康保险为员工提供团体保障，以具有竞争力的价格提供全面的医疗福利。它提高员工满意度、改善保留率并展示企业责任。", sections: { coverage: [{ heading: "员工保障", content: "为所有符合条件的员工提供全面的医疗保障。" }, { heading: "受抚养人", content: "配偶和子女的可选保障。" }, { heading: "健康计划", content: "包括健康筛查、健身计划和心理健康支持。" }], exclusions: ["美容手术", "实验性治疗", "因工作场所疏忽造成的状况", "既往症（取决于保单）"], features: ["团体折扣", "灵活的计划选项", "员工健康计划", "简单的管理", "具有竞争力的团体费率"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰就业和保险法规。", cta: { title: "雇主解决方案", description: "为您的员工提供全面的健康保障。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Zdrowotne Korporacyjne", overview: "Ubezpieczenie zdrowotne korporacyjne zapewnia grupowe pokrycie dla pracowników, oferując kompleksowe świadczenia medyczne w konkurencyjnych cenach. Poprawia zadowolenie pracowników, zwiększa retencję i wykazuje odpowiedzialność korporacyjną.", sections: { coverage: [{ heading: "Pokrycie pracowników", content: "Kompleksowe pokrycie medyczne dla wszystkich uprawnionych pracowników." }, { heading: "Osoby na utrzymaniu", content: "Opcjonalne pokrycie dla małżonków i dzieci." }, { heading: "Programy wellness", content: "Obejmuje badania zdrowotne, programy fitness i wsparcie zdrowia psychicznego." }], exclusions: ["Procedury kosmetyczne", "Leczenie eksperymentalne", "Warunki z zaniedbania w miejscu pracy", "Istniejące wcześniej warunki (w zależności od polisy)"], features: ["Rabaty grupowe", "Elastyczne opcje planu", "Programy wellness pracowników", "Łatwa administracja", "Konkurencyjne stawki grupowe"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami dotyczącymi zatrudnienia i ubezpieczeń.", cta: { title: "Rozwiązania dla pracodawców", description: "Zapewnij swoim pracownikom kompleksowe pokrycie zdrowotne.", button: "Skontaktuj się z nami" } },
  },

  // ============ GENERAL INSURANCE PAGES (5) ============
  homeInsurance: {
    en: { title: "Home Insurance", overview: "Home insurance protects your property and belongings against damage, theft, and loss. It provides peace of mind and financial security for one of your most valuable assets.", sections: { coverage: [{ heading: "Buildings Coverage", content: "Covers the structure of your home including walls, roof, and permanent fixtures." }, { heading: "Contents Coverage", content: "Protects your personal belongings including furniture, electronics, and clothing." }, { heading: "Accidental Damage", content: "Optional coverage for accidental damage to your home and contents." }], exclusions: ["Damage from wear and tear", "Damage from poor maintenance", "Claims not reported within 30 days", "Damage from unoccupancy over 30 days"], features: ["24/7 emergency support", "Fast claims processing", "Flexible coverage options", "Discounts for security measures", "Optional accidental damage cover"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish insurance regulations.", cta: { title: "Protect Your Home", description: "Get comprehensive home insurance coverage today.", button: "Contact Us" } },
    zh: { title: "家庭保险", overview: "家庭保险保护您的财产和物品免受损坏、盗窃和损失。它为您最有价值的资产之一提供安心和财务安全。", sections: { coverage: [{ heading: "建筑物保障", content: "涵盖您家的结构，包括墙壁、屋顶和永久固定装置。" }, { heading: "内容保障", content: "保护您的个人物品，包括家具、电子产品和衣服。" }, { heading: "意外损坏", content: "对您的家和内容的意外损坏的可选保障。" }], exclusions: ["磨损造成的损坏", "由于维护不当造成的损坏", "未在30天内报告的索赔", "超过30天无人居住造成的损坏"], features: ["24/7紧急支持", "快速理赔处理", "灵活的保障选项", "安全措施折扣", "可选的意外损坏保障"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰保险法规。", cta: { title: "保护您的家", description: "立即获得全面的家庭保险保障。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Domu", overview: "Ubezpieczenie domu chroni Twoją nieruchomość i rzeczy przed uszkodzeniem, kradzieżą i stratą. Zapewnia spokój ducha i bezpieczeństwo finansowe dla jednego z Twoich najcenniejszych aktywów.", sections: { coverage: [{ heading: "Pokrycie budynku", content: "Obejmuje strukturę Twojego domu, w tym ściany, dach i stałe urządzenia." }, { heading: "Pokrycie zawartości", content: "Chroni Twoje osobiste rzeczy, w tym meble, elektronikę i odzież." }, { heading: "Uszkodzenie przypadkowe", content: "Opcjonalne pokrycie przypadkowego uszkodzenia Twojego domu i zawartości." }], exclusions: ["Uszkodzenia z powodu zużycia", "Uszkodzenia z powodu złej konserwacji", "Roszczenia nie zgłoszone w ciągu 30 dni", "Uszkodzenia z powodu nieobsadzoności powyżej 30 dni"], features: ["Wsparcie awaryjne 24/7", "Szybkie przetwarzanie roszczeń", "Elastyczne opcje pokrycia", "Rabaty za środki bezpieczeństwa", "Opcjonalne pokrycie uszkodzenia przypadkowego"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami ubezpieczeniowymi.", cta: { title: "Chroń swój dom", description: "Uzyskaj kompleksowe ubezpieczenie domu dzisiaj.", button: "Skontaktuj się z nami" } },
  },

  motorInsurance: {
    en: { title: "Motor Insurance", overview: "Motor insurance provides comprehensive coverage for your vehicle against damage, theft, and third-party liability. It's a legal requirement and essential protection for drivers.", sections: { coverage: [{ heading: "Third-Party Liability", content: "Covers damage or injury you cause to others. Legally required." }, { heading: "Comprehensive Coverage", content: "Includes third-party plus theft, fire, and accidental damage." }, { heading: "Breakdown Cover", content: "Optional coverage for roadside assistance and recovery." }], exclusions: ["Damage from racing or track use", "Driving under influence", "Damage from poor maintenance", "Claims without valid license"], features: ["24/7 breakdown assistance", "No-claims discount", "Flexible payment options", "Windscreen cover available", "Courtesy car provision"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish motor insurance regulations.", cta: { title: "Get a Quote", description: "Protect your vehicle with comprehensive motor insurance.", button: "Contact Us" } },
    zh: { title: "汽车保险", overview: "汽车保险为您的车辆提供全面保障，防止损坏、盗窃和第三方责任。这是法律要求，也是驾驶员的基本保护。", sections: { coverage: [{ heading: "第三方责任", content: "涵盖您对他人造成的损害或伤害。法律要求。" }, { heading: "全面保障", content: "包括第三方加盗窃、火灾和意外损坏。" }, { heading: "故障保障", content: "路边援助和救援的可选保障。" }], exclusions: ["赛车或赛道使用造成的损坏", "酒后驾驶", "由于维护不当造成的损坏", "没有有效驾照的索赔"], features: ["24/7故障援助", "无索赔折扣", "灵活的支付选项", "可用的挡风玻璃保障", "礼仪车提供"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰汽车保险法规。", cta: { title: "获取报价", description: "通过全面的汽车保险保护您的车辆。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Samochodu", overview: "Ubezpieczenie samochodu zapewnia kompleksowe pokrycie Twojego pojazdu przed uszkodzeniem, kradzieżą i odpowiedzialnością wobec trzecich stron. Jest to wymóg prawny i niezbędna ochrona dla kierowców.", sections: { coverage: [{ heading: "Odpowiedzialność wobec trzecich stron", content: "Obejmuje uszkodzenia lub obrażenia, które powodują innym. Wymagane prawnie." }, { heading: "Kompleksowe pokrycie", content: "Obejmuje odpowiedzialność wobec trzecich stron plus kradzież, pożar i uszkodzenie przypadkowe." }, { heading: "Pokrycie awarii", content: "Opcjonalne pokrycie pomocy na drodze i odholowania." }], exclusions: ["Uszkodzenia z wyścigów lub użytku na torze", "Jazda pod wpływem", "Uszkodzenia z powodu złej konserwacji", "Roszczenia bez ważnego prawa jazdy"], features: ["Pomoc w awarii 24/7", "Rabat bez roszczeń", "Elastyczne opcje płatności", "Dostępne pokrycie szyby przedniej", "Zapewnienie samochodu zastępczego"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami dotyczącymi ubezpieczenia samochodu.", cta: { title: "Uzyskaj wycenę", description: "Chroń swój pojazd dzięki kompleksowemu ubezpieczeniu samochodu.", button: "Skontaktuj się z nami" } },
  },

  businessInsurance: {
    en: { title: "Business Insurance", overview: "Business insurance protects your company against financial losses from property damage, liability claims, and business interruption. It's essential for business continuity and growth.", sections: { coverage: [{ heading: "Property Coverage", content: "Covers buildings, equipment, and inventory against damage or theft." }, { heading: "Liability Coverage", content: "Protects against claims from customers, employees, or third parties." }, { heading: "Business Interruption", content: "Covers lost income if your business is forced to close temporarily." }], exclusions: ["Damage from poor maintenance", "Claims from illegal activities", "Damage from war or terrorism", "Claims not reported within 30 days"], features: ["Tailored coverage options", "Risk assessment support", "Claims management assistance", "Competitive business rates", "Flexible payment terms"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish business insurance regulations.", cta: { title: "Protect Your Business", description: "Secure your business with comprehensive insurance coverage.", button: "Contact Us" } },
    zh: { title: "商业保险", overview: "商业保险保护您的公司免受财产损坏、责任索赔和业务中断造成的财务损失。这对于业务连续性和增长至关重要。", sections: { coverage: [{ heading: "财产保障", content: "涵盖建筑物、设备和库存免受损坏或盗窃。" }, { heading: "责任保障", content: "保护免受来自客户、员工或第三方的索赔。" }, { heading: "业务中断", content: "如果您的业务被迫临时关闭，涵盖损失的收入。" }], exclusions: ["由于维护不当造成的损坏", "来自非法活动的索赔", "来自战争或恐怖主义的损坏", "未在30天内报告的索赔"], features: ["定制的保障选项", "风险评估支持", "索赔管理协助", "具有竞争力的商业费率", "灵活的支付条款"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰商业保险法规。", cta: { title: "保护您的业务", description: "通过全面的保险保障确保您的业务安全。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Biznesu", overview: "Ubezpieczenie biznesu chroni Twoją firmę przed stratami finansowymi z powodu uszkodzenia mienia, roszczeń z tytułu odpowiedzialności i przerwania działalności. Jest niezbędne dla ciągłości biznesu i wzrostu.", sections: { coverage: [{ heading: "Pokrycie mienia", content: "Obejmuje budynki, sprzęt i zapasy przed uszkodzeniem lub kradzieżą." }, { heading: "Pokrycie odpowiedzialności", content: "Chroni przed roszczeniami od klientów, pracowników lub stron trzecich." }, { heading: "Przerwanie działalności", content: "Obejmuje utracone dochody, jeśli Twoja firma zostanie zmuszona do czasowego zamknięcia." }], exclusions: ["Uszkodzenia z powodu złej konserwacji", "Roszczenia z działań nielegalnych", "Uszkodzenia z powodu wojny lub terroryzmu", "Roszczenia nie zgłoszone w ciągu 30 dni"], features: ["Opcje pokrycia dostosowane do potrzeb", "Wsparcie oceny ryzyka", "Pomoc w zarządzaniu roszczeniami", "Konkurencyjne stawki biznesowe", "Elastyczne warunki płatności"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami dotyczącymi ubezpieczenia biznesu.", cta: { title: "Chroń swoją firmę", description: "Zabezpiecz swoją firmę dzięki kompleksowemu ubezpieczeniu.", button: "Skontaktuj się z nami" } },
  },

  landlordInsurance: {
    en: { title: "Landlord Insurance", overview: "Landlord insurance protects your rental property and provides liability coverage for tenants and visitors. It covers rental income loss and property damage specific to rental properties.", sections: { coverage: [{ heading: "Buildings Coverage", content: "Covers the structure of your rental property against damage." }, { heading: "Liability Coverage", content: "Protects against claims from tenants or visitors injured on your property." }, { heading: "Rent Protection", content: "Covers lost rental income if tenants default or property becomes uninhabitable." }], exclusions: ["Damage from tenant negligence", "Claims not reported within 30 days", "Damage from poor maintenance", "Unoccupied properties over 30 days"], features: ["Tenant vetting support", "Legal expense cover", "Emergency repair cover", "Competitive landlord rates", "Flexible coverage options"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish landlord insurance regulations.", cta: { title: "Protect Your Investment", description: "Secure your rental property with landlord insurance.", button: "Contact Us" } },
    zh: { title: "房东保险", overview: "房东保险保护您的出租物业并为租户和访客提供责任保障。它涵盖特定于出租物业的租金收入损失和财产损坏。", sections: { coverage: [{ heading: "建筑物保障", content: "涵盖您的出租物业的结构免受损坏。" }, { heading: "责任保障", content: "保护免受在您的物业上受伤的租户或访客的索赔。" }, { heading: "租金保护", content: "如果租户违约或物业变得不适合居住，涵盖损失的租金收入。" }], exclusions: ["由租户疏忽造成的损坏", "未在30天内报告的索赔", "由于维护不当造成的损坏", "超过30天无人居住的物业"], features: ["租户审查支持", "法律费用保障", "紧急维修保障", "具有竞争力的房东费率", "灵活的保障选项"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰房东保险法规。", cta: { title: "保护您的投资", description: "通过房东保险确保您的出租物业安全。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Właściciela Nieruchomości", overview: "Ubezpieczenie właściciela nieruchomości chroni Twoją wynajmowaną nieruchomość i zapewnia pokrycie odpowiedzialności dla najemców i odwiedzających. Obejmuje utratę dochodu z wynajmu i uszkodzenia mienia specyficzne dla wynajmowanych nieruchomości.", sections: { coverage: [{ heading: "Pokrycie budynku", content: "Obejmuje strukturę Twojej wynajmowanej nieruchomości przed uszkodzeniem." }, { heading: "Pokrycie odpowiedzialności", content: "Chroni przed roszczeniami od najemców lub odwiedzających rannych na Twojej nieruchomości." }, { heading: "Ochrona czynszu", content: "Obejmuje utracony dochód z wynajmu, jeśli najemcy nie wywiążą się lub nieruchomość stanie się niezamieszkana." }], exclusions: ["Uszkodzenia z powodu zaniedbania najemcy", "Roszczenia nie zgłoszone w ciągu 30 dni", "Uszkodzenia z powodu złej konserwacji", "Nieruchomości nieobsadzone powyżej 30 dni"], features: ["Wsparcie weryfikacji najemcy", "Pokrycie wydatków prawnych", "Pokrycie naprawy awaryjnej", "Konkurencyjne stawki dla właścicieli", "Elastyczne opcje pokrycia"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami dotyczącymi ubezpieczenia właścicieli nieruchomości.", cta: { title: "Chroń swoją inwestycję", description: "Zabezpiecz swoją wynajmowaną nieruchomość dzięki ubezpieczeniu właściciela.", button: "Skontaktuj się z nami" } },
  },

  liabilityInsurance: {
    en: { title: "Liability Insurance", overview: "Liability insurance protects you against legal and financial consequences of injuring someone or damaging their property. It's essential for businesses and individuals with significant assets.", sections: { coverage: [{ heading: "Bodily Injury", content: "Covers medical expenses and compensation for injuries you cause to others." }, { heading: "Property Damage", content: "Covers damage to others' property caused by you or your business." }, { heading: "Legal Defense", content: "Covers legal fees and court costs for defending claims." }], exclusions: ["Intentional harm", "Criminal acts", "Contractual liability", "Professional negligence (without endorsement)"], features: ["High coverage limits available", "Legal support services", "24/7 claims support", "Competitive rates", "Flexible policy options"] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish liability insurance regulations.", cta: { title: "Get Protected", description: "Secure your financial future with liability insurance.", button: "Contact Us" } },
    zh: { title: "责任保险", overview: "责任保险保护您免受伤害他人或损坏其财产的法律和财务后果。对于拥有重大资产的企业和个人来说，这是必不可少的。", sections: { coverage: [{ heading: "人身伤害", content: "涵盖您对他人造成的伤害的医疗费用和赔偿。" }, { heading: "财产损坏", content: "涵盖您或您的业务造成的他人财产损坏。" }, { heading: "法律辩护", content: "涵盖为辩护索赔的法律费用和诉讼费用。" }], exclusions: ["故意伤害", "犯罪行为", "合同责任", "专业过失（没有认可）"], features: ["提供高保障限额", "法律支持服务", "24/7索赔支持", "具有竞争力的费率", "灵活的保单选项"] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰责任保险法规。", cta: { title: "获得保护", description: "通过责任保险确保您的财务未来。", button: "联系我们" } },
    pl: { title: "Ubezpieczenie Odpowiedzialności Cywilnej", overview: "Ubezpieczenie odpowiedzialności cywilnej chroni Cię przed konsekwencjami prawnymi i finansowymi zranienia kogoś lub uszkodzenia jego mienia. Jest niezbędne dla firm i osób posiadających znaczące aktywa.", sections: { coverage: [{ heading: "Obrażenia ciała", content: "Obejmuje wydatki medyczne i odszkodowanie za obrażenia, które powodują innym." }, { heading: "Uszkodzenie mienia", content: "Obejmuje uszkodzenia mienia innych osób spowodowane przez Ciebie lub Twoją firmę." }, { heading: "Obrona prawna", content: "Obejmuje opłaty prawne i koszty sądowe za obronę roszczeń." }], exclusions: ["Celne krzywdzenie", "Działania kryminalne", "Odpowiedzialność umowna", "Zaniedbanie zawodowe (bez potwierdzenia)"], features: ["Dostępne wysokie limity pokrycia", "Usługi wsparcia prawnego", "Wsparcie roszczeń 24/7", "Konkurencyjne stawki", "Elastyczne opcje polisy"] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami dotyczącymi ubezpieczenia odpowiedzialności cywilnej.", cta: { title: "Uzyskaj ochronę", description: "Zabezpiecz swoją przyszłość finansową dzięki ubezpieczeniu odpowiedzialności cywilnej.", button: "Skontaktuj się z nami" } },
  },

  // ============ INVESTMENTS PAGES (6) ============
  savingsPlans: {
    en: { title: "Savings Plans", overview: "Savings plans help you build wealth steadily through regular monthly contributions. Even small regular investments can grow significantly over time through the power of compound returns.", sections: { keyAspects: [{ heading: "Regular Contributions", content: "Invest fixed amounts monthly to build discipline and consistency." }, { heading: "Flexible Amounts", content: "Start with amounts that suit your budget and increase over time." }, { heading: "Diversified Portfolios", content: "Your money is invested across multiple asset classes for risk management." }, { heading: "Long-term Growth", content: "Benefit from compound returns and market growth over decades." }], taxBenefits: [{ heading: "Tax-Efficient Growth", content: "Investment growth is managed tax-efficiently within the plan." }, { heading: "Reinvested Dividends", content: "Dividends are automatically reinvested for compound growth." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment regulations.", cta: { title: "Start Investing", description: "Begin your investment journey with a savings plan.", button: "Contact Us" } },
    zh: { title: "储蓄计划", overview: "储蓄计划帮助您通过定期月度缴款稳步积累财富。即使很小的定期投资也可以通过复利回报的力量在一段时间内显著增长。", sections: { keyAspects: [{ heading: "定期缴款", content: "每月投资固定金额以建立纪律和一致性。" }, { heading: "灵活金额", content: "从适合您预算的金额开始，并随时间增加。" }, { heading: "多元化投资组合", content: "您的资金投资于多个资产类别以进行风险管理。" }, { heading: "长期增长", content: "受益于几十年的复利回报和市场增长。" }], taxBenefits: [{ heading: "税收高效增长", content: "投资增长在计划内以税收高效的方式管理。" }, { heading: "再投资股息", content: "股息自动再投资以实现复利增长。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资法规。", cta: { title: "开始投资", description: "通过储蓄计划开始您的投资之旅。", button: "联系我们" } },
    pl: { title: "Plany Oszczędnościowe", overview: "Plany oszczędnościowe pomagają w stopniowym budowaniu bogactwa poprzez regularne miesięczne wpłaty. Nawet małe regularne inwestycje mogą znacznie wzrosnąć w czasie dzięki sile zwrotów złożonych.", sections: { keyAspects: [{ heading: "Regularne składki", content: "Inwestuj stałe kwoty co miesiąc, aby budować dyscyplinę i spójność." }, { heading: "Elastyczne kwoty", content: "Zacznij od kwot dostosowanych do Twojego budżetu i zwiększaj je w czasie." }, { heading: "Zdywersyfikowane portfele", content: "Twoje pieniądze są inwestowane w wiele klas aktywów w celu zarządzania ryzykiem." }, { heading: "Wzrost długoterminowy", content: "Korzystaj ze zwrotów złożonych i wzrostu rynku przez dziesięciolecia." }], taxBenefits: [{ heading: "Wzrost efektywny podatkowo", content: "Wzrost inwestycji jest zarządzany efektywnie podatkowo w ramach planu." }, { heading: "Reinwestowane dywidendy", content: "Dywidendy są automatycznie reinwestowane dla wzrostu złożonego." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi.", cta: { title: "Zacznij inwestować", description: "Zacznij swoją podrót inwestycyjną za pomocą planu oszczędnościowego.", button: "Skontaktuj się z nami" } },
  },

  investmentBonds: {
    en: { title: "Investment Bonds", overview: "Investment bonds are a tax-efficient way to invest a lump sum across a wide range of funds. They offer flexibility, growth potential, and various risk levels to suit all investors.", sections: { keyAspects: [{ heading: "Lump Sum Investment", content: "Invest a large amount at once across multiple funds." }, { heading: "Flexibility", content: "Access your money with minimal penalties after the initial term." }, { heading: "Growth Potential", content: "Benefit from professional fund management and market growth." }, { heading: "Various Risk Levels", content: "Choose from conservative to aggressive investment strategies." }], taxBenefits: [{ heading: "Tax Deferral", content: "No tax paid on growth until you withdraw funds." }, { heading: "Partial Withdrawal", content: "Withdraw up to 5% annually tax-free." }, { heading: "Inheritance Tax Efficiency", content: "Can be structured for inheritance tax planning." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment regulations.", cta: { title: "Invest Now", description: "Grow your wealth with an investment bond.", button: "Contact Us" } },
    zh: { title: "投资债券", overview: "投资债券是一种税收高效的方式，可以将一笔大额投资分散在广泛的基金中。它们提供灵活性、增长潜力和各种风险水平，适合所有投资者。", sections: { keyAspects: [{ heading: "一次性投资", content: "一次性投资大额资金到多个基金中。" }, { heading: "灵活性", content: "在初始期限后以最少的处罚获得您的资金。" }, { heading: "增长潜力", content: "受益于专业基金管理和市场增长。" }, { heading: "各种风险水平", content: "从保守到激进的投资策略中选择。" }], taxBenefits: [{ heading: "税收延期", content: "在您提取资金之前，对增长不征税。" }, { heading: "部分提取", content: "每年提取最多5%免税。" }, { heading: "继承税收效率", content: "可以为继承税规划而构建。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资法规。", cta: { title: "立即投资", description: "通过投资债券增加您的财富。", button: "联系我们" } },
    pl: { title: "Obligacje Inwestycyjne", overview: "Obligacje inwestycyjne to opłacalny podatkowo sposób inwestowania dużej sumy w szeroką gamę funduszy. Oferują elastyczność, potencjał wzrostu i różne poziomy ryzyka dla wszystkich inwestorów.", sections: { keyAspects: [{ heading: "Inwestycja ryczałtowa", content: "Zainwestuj dużą kwotę na raz w wiele funduszy." }, { heading: "Elastyczność", content: "Uzyskaj dostęp do swoich pieniędzy z minimalnymi karami po początkowym okresie." }, { heading: "Potencjał wzrostu", content: "Korzystaj z profesjonalnego zarządzania funduszami i wzrostu rynku." }, { heading: "Różne poziomy ryzyka", content: "Wybierz z konserwatywnych do agresywnych strategii inwestycyjnych." }], taxBenefits: [{ heading: "Odroczenie podatku", content: "Brak podatku od wzrostu do czasu wycofania środków." }, { heading: "Częściowe wycofanie", content: "Wycofaj do 5% rocznie bez podatku." }, { heading: "Efektywność podatku od spadków", content: "Można strukturyzować do planowania podatku od spadków." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi.", cta: { title: "Inwestuj teraz", description: "Zwiększ swoją majątek dzięki obligacji inwestycyjnej.", button: "Skontaktuj się z nami" } },
  },

  portfolioManagement: {
    en: { title: "Portfolio Management", overview: "Professional portfolio management provides expert guidance in building and maintaining a diversified investment portfolio tailored to your goals and risk tolerance. Our advisors work with you to optimize returns.", sections: { keyAspects: [{ heading: "Expert Guidance", content: "Benefit from experienced investment professionals." }, { heading: "Personalized Strategy", content: "Create a portfolio aligned with your financial goals." }, { heading: "Regular Rebalancing", content: "Keep your portfolio optimized as markets change." }, { heading: "Risk Management", content: "Diversify across asset classes to manage risk." }], taxBenefits: [{ heading: "Tax-Efficient Strategies", content: "Optimize your portfolio for tax efficiency." }, { heading: "Strategic Asset Allocation", content: "Allocate assets to maximize after-tax returns." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment and financial advisory regulations.", cta: { title: "Get Advice", description: "Speak with our portfolio management experts.", button: "Contact Us" } },
    zh: { title: "投资组合管理", overview: "专业投资组合管理提供专家指导，帮助您建立和维护根据您的目标和风险承受能力定制的多元化投资组合。我们的顾问与您合作以优化回报。", sections: { keyAspects: [{ heading: "专家指导", content: "受益于经验丰富的投资专业人士。" }, { heading: "个性化策略", content: "创建与您的财务目标相一致的投资组合。" }, { heading: "定期再平衡", content: "随着市场变化保持您的投资组合优化。" }, { heading: "风险管理", content: "跨资产类别多元化以管理风险。" }], taxBenefits: [{ heading: "税收高效策略", content: "优化您的投资组合以实现税收效率。" }, { heading: "战略性资产配置", content: "分配资产以最大化税后回报。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资和财务顾问法规。", cta: { title: "获取建议", description: "与我们的投资组合管理专家交流。", button: "联系我们" } },
    pl: { title: "Zarządzanie Portfelem", overview: "Profesjonalne zarządzanie portfelem zapewnia fachowe wskazówki w budowaniu i utrzymywaniu zdywersyfikowanego portfela inwestycyjnego dostosowanego do Twoich celów i tolerancji ryzyka. Nasi doradcy pracują z Tobą, aby zoptymalizować zwroty.", sections: { keyAspects: [{ heading: "Fachowe wskazówki", content: "Korzystaj z doświadczonych specjalistów inwestycyjnych." }, { heading: "Spersonalizowana strategia", content: "Stwórz portfel zgodny z Twoimi celami finansowymi." }, { heading: "Regularne przywracanie równowagi", content: "Utrzymuj swój portfel zoptymalizowany w miarę zmian rynku." }, { heading: "Zarządzanie ryzykiem", content: "Zdywersyfikuj się w klasach aktywów, aby zarządzać ryzykiem." }], taxBenefits: [{ heading: "Strategie efektywne podatkowo", content: "Zoptymalizuj swój portfel pod kątem efektywności podatkowej." }, { heading: "Strategiczna alokacja aktywów", content: "Alokuj aktywa, aby zmaksymalizować zwroty po opodatkowaniu." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi i doradztwa finansowego.", cta: { title: "Uzyskaj poradę", description: "Porozmawiaj z naszymi ekspertami ds. zarządzania portfelem.", button: "Skontaktuj się z nami" } },
  },

  stocksShares: {
    en: { title: "Stocks & Shares", overview: "Stocks and shares offer direct ownership in companies with potential for capital growth and dividend income. They're suitable for investors with medium to long-term horizons and moderate to high risk tolerance.", sections: { keyAspects: [{ heading: "Ownership Stakes", content: "Own a piece of real companies and benefit from their growth." }, { heading: "Dividend Income", content: "Receive regular income from company dividends." }, { heading: "Capital Growth", content: "Benefit from share price appreciation over time." }, { heading: "Liquidity", content: "Easily buy and sell shares through stock exchanges." }], taxBenefits: [{ heading: "Capital Gains Tax", content: "Benefit from capital gains tax allowances." }, { heading: "Dividend Allowance", content: "Receive tax-free dividend income up to your allowance." }, { heading: "ISA Wrapper", content: "Hold shares in an ISA for tax-free growth." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment regulations.", cta: { title: "Start Trading", description: "Begin investing in stocks and shares today.", button: "Contact Us" } },
    zh: { title: "股票和股份", overview: "股票和股份提供对公司的直接所有权，具有资本增长和股息收入的潜力。它们适合具有中期至长期投资期限和中等至高风险承受能力的投资者。", sections: { keyAspects: [{ heading: "所有权权益", content: "拥有真实公司的一部分并受益于其增长。" }, { heading: "股息收入", content: "从公司股息中获得定期收入。" }, { heading: "资本增长", content: "随时间受益于股价升值。" }, { heading: "流动性", content: "通过股票交易所轻松买卖股票。" }], taxBenefits: [{ heading: "资本利得税", content: "受益于资本利得税津贴。" }, { heading: "股息津贴", content: "获得津贴范围内的免税股息收入。" }, { heading: "ISA包装", content: "在ISA中持有股票以实现免税增长。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资法规。", cta: { title: "开始交易", description: "立即开始投资股票和股份。", button: "联系我们" } },
    pl: { title: "Akcje i Udziały", overview: "Akcje i udziały oferują bezpośrednią własność w firmach z potencjałem wzrostu kapitału i dochodu z dywidend. Są odpowiednie dla inwestorów o średnim do długoterminowym horyzoncie i średniej do wysokiej tolerancji ryzyka.", sections: { keyAspects: [{ heading: "Udziały własnościowe", content: "Posiadaj część rzeczywistych firm i korzystaj z ich wzrostu." }, { heading: "Dochód z dywidend", content: "Otrzymuj regularne dochody z dywidend spółek." }, { heading: "Wzrost kapitału", content: "Korzystaj z aprecjacji ceny akcji w czasie." }, { heading: "Płynność", content: "Łatwo kupuj i sprzedawaj akcje na giełdach papierów wartościowych." }], taxBenefits: [{ heading: "Podatek od zysków kapitałowych", content: "Korzystaj z ulg w podatku od zysków kapitałowych." }, { heading: "Ulga na dywidendy", content: "Otrzymuj dochód z dywidend bez podatku do wysokości ulgi." }, { heading: "Opakowanie ISA", content: "Trzymaj akcje w ISA dla wzrostu bez podatku." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi.", cta: { title: "Zacznij handlować", description: "Zacznij inwestować w akcje i udziały dzisiaj.", button: "Skontaktuj się z nami" } },
  },

  educationSavingPlans: {
    en: { title: "Education Saving Plans", overview: "Education saving plans help parents build dedicated funds for their children's education. They combine regular contributions with investment growth to ensure funds are available when needed for tuition and education expenses.", sections: { keyAspects: [{ heading: "Regular Contributions", content: "Build education funds through consistent monthly or annual contributions." }, { heading: "Age-Based Strategy", content: "Portfolio automatically adjusts as your child approaches school age." }, { heading: "Tax Efficiency", content: "Benefit from tax-efficient growth of education funds." }, { heading: "Flexibility", content: "Use funds for any education-related expenses." }], taxBenefits: [{ heading: "Tax-Free Growth", content: "Investment growth is tax-free within the plan." }, { heading: "Contribution Relief", content: "Some contributions may qualify for tax relief." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment regulations.", cta: { title: "Start Saving", description: "Begin planning for your child's education today.", button: "Contact Us" } },
    zh: { title: "教育储蓄计划", overview: "教育储蓄计划帮助父母为孩子的教育建立专项基金。它们将定期缴款与投资增长相结合，以确保在需要时有资金用于学费和教育费用。", sections: { keyAspects: [{ heading: "定期缴款", content: "通过一致的月度或年度缴款建立教育基金。" }, { heading: "基于年龄的策略", content: "随着您的孩子接近学龄，投资组合会自动调整。" }, { heading: "税收效率", content: "受益于教育基金的税收高效增长。" }, { heading: "灵活性", content: "将资金用于任何教育相关费用。" }], taxBenefits: [{ heading: "免税增长", content: "计划内的投资增长是免税的。" }, { heading: "缴款减免", content: "某些缴款可能符合税收减免的条件。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资法规。", cta: { title: "开始储蓄", description: "立即开始为孩子的教育规划。", button: "联系我们" } },
    pl: { title: "Plany Oszczędzania na Edukację", overview: "Plany oszczędzania na edukację pomagają rodzicom budować dedykowane fundusze na edukację swoich dzieci. Łączą regularne wpłaty ze wzrostem inwestycji, aby zapewnić dostępność środków w razie potrzeby na czesne i wydatki edukacyjne.", sections: { keyAspects: [{ heading: "Regularne składki", content: "Buduj fundusze edukacyjne poprzez spójne miesięczne lub roczne wpłaty." }, { heading: "Strategia oparta na wieku", content: "Portfel automatycznie się dostosowuje, gdy Twoje dziecko zbliża się do wieku szkolnego." }, { heading: "Efektywność podatkowa", content: "Korzystaj z efektywnego podatkowo wzrostu funduszy edukacyjnych." }, { heading: "Elastyczność", content: "Używaj środków na wszelkie wydatki związane z edukacją." }], taxBenefits: [{ heading: "Wzrost wolny od podatku", content: "Wzrost inwestycji w ramach planu jest wolny od podatku." }, { heading: "Ulga na składki", content: "Niektóre składki mogą kwalifikować się do ulgi podatkowej." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi.", cta: { title: "Zacznij oszczędzać", description: "Zacznij planować edukację swojego dziecka dzisiaj.", button: "Skontaktuj się z nami" } },
  },

  structuredProducts: {
    en: { title: "Structured Products", overview: "Structured products combine capital protection features with enhanced return potential through derivatives and customized payoff structures. They're designed for specific investment goals and risk profiles.", sections: { keyAspects: [{ heading: "Capital Protection", content: "Protect your initial investment with guaranteed return of principal at maturity." }, { heading: "Enhanced Returns", content: "Participate in market upside with defined maximum returns." }, { heading: "Customized Structures", content: "Design products tailored to your specific investment objectives." }, { heading: "Defined Risk", content: "Know your maximum potential loss from the start." }], taxBenefits: [{ heading: "Structured Tax Planning", content: "Design products with tax efficiency in mind." }, { heading: "Timing Flexibility", content: "Choose maturity dates aligned with your tax planning." }] }, regulatory: "Regulated by the Central Bank of Ireland. Complies with Irish investment regulations and MiFID II requirements.", cta: { title: "Explore Options", description: "Discover structured products suited to your goals.", button: "Contact Us" } },
    zh: { title: "结构化产品", overview: "结构化产品通过衍生品和定制收益结构，将资本保护特征与增强回报潜力相结合。它们专为特定投资目标和风险概况而设计。", sections: { keyAspects: [{ heading: "资本保护", content: "通过保证在到期时返还本金来保护您的初始投资。" }, { heading: "增强回报", content: "以定义的最大回报参与市场上升。" }, { heading: "定制结构", content: "设计根据您的特定投资目标定制的产品。" }, { heading: "定义的风险", content: "从一开始就知道您的最大潜在损失。" }], taxBenefits: [{ heading: "结构化税收规划", content: "设计考虑税收效率的产品。" }, { heading: "时间灵活性", content: "选择与您的税收规划相一致的到期日期。" }] }, regulatory: "由爱尔兰中央银行监管。符合爱尔兰投资法规和MiFID II要求。", cta: { title: "探索选项", description: "发现适合您目标的结构化产品。", button: "联系我们" } },
    pl: { title: "Produkty Strukturyzowane", overview: "Produkty strukturyzowane łączą cechy ochrony kapitału ze zwiększonym potencjałem zwrotu poprzez instrumenty pochodne i dostosowane struktury wypłat. Są zaprojektowane dla określonych celów inwestycyjnych i profili ryzyka.", sections: { keyAspects: [{ heading: "Ochrona kapitału", content: "Chroń swoją początkową inwestycję poprzez gwarantowany zwrot kapitału w terminie zapadalności." }, { heading: "Zwiększone zwroty", content: "Uczestnicz w wzroście rynku ze zdefiniowanymi maksymalnymi zwrotami." }, { heading: "Struktury dostosowane", content: "Zaprojektuj produkty dostosowane do Twoich konkretnych celów inwestycyjnych." }, { heading: "Zdefiniowane ryzyko", content: "Znaj swoją maksymalną potencjalną stratę od samego początku." }], taxBenefits: [{ heading: "Strukturyzowane planowanie podatkowe", content: "Zaprojektuj produkty z myślą o efektywności podatkowej." }, { heading: "Elastyczność czasowa", content: "Wybierz daty zapadalności zgodne z Twoim planem podatkowym." }] }, regulatory: "Regulowana przez Centralny Bank Irlandii. Zgodna z irlandzkimi przepisami inwestycyjnymi i wymogami MiFID II.", cta: { title: "Poznaj opcje", description: "Odkryj produkty strukturyzowane dostosowane do Twoich celów.", button: "Skontaktuj się z nami" } },
  },
};

export function getDetailPageTranslation(page: string, language: Language = 'en'): any {
  const pageTranslations = (allDetailTranslations as any)[page];
  if (!pageTranslations) return null;
  return pageTranslations[language] || pageTranslations.en;
}
