CREATE TABLE `rolePermissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`role` enum('admin','manager','support','staff') NOT NULL,
	`canViewClients` enum('true','false') NOT NULL DEFAULT 'true',
	`canEditClients` enum('true','false') NOT NULL DEFAULT 'true',
	`canDeleteClients` enum('true','false') NOT NULL DEFAULT 'false',
	`canArchiveClients` enum('true','false') NOT NULL DEFAULT 'false',
	`canRestoreClients` enum('true','false') NOT NULL DEFAULT 'false',
	`canViewKYC` enum('true','false') NOT NULL DEFAULT 'true',
	`canApproveKYC` enum('true','false') NOT NULL DEFAULT 'false',
	`canRejectKYC` enum('true','false') NOT NULL DEFAULT 'false',
	`canReviewDocuments` enum('true','false') NOT NULL DEFAULT 'false',
	`canViewPolicies` enum('true','false') NOT NULL DEFAULT 'true',
	`canEditPolicies` enum('true','false') NOT NULL DEFAULT 'false',
	`canDeletePolicies` enum('true','false') NOT NULL DEFAULT 'false',
	`canViewForms` enum('true','false') NOT NULL DEFAULT 'true',
	`canEditForms` enum('true','false') NOT NULL DEFAULT 'false',
	`canCreateForms` enum('true','false') NOT NULL DEFAULT 'false',
	`canDeleteForms` enum('true','false') NOT NULL DEFAULT 'false',
	`canViewCampaigns` enum('true','false') NOT NULL DEFAULT 'true',
	`canCreateCampaigns` enum('true','false') NOT NULL DEFAULT 'false',
	`canSendCampaigns` enum('true','false') NOT NULL DEFAULT 'false',
	`canDeleteCampaigns` enum('true','false') NOT NULL DEFAULT 'false',
	`canManageTeam` enum('true','false') NOT NULL DEFAULT 'false',
	`canInviteMembers` enum('true','false') NOT NULL DEFAULT 'false',
	`canRemoveMembers` enum('true','false') NOT NULL DEFAULT 'false',
	`canChangeRoles` enum('true','false') NOT NULL DEFAULT 'false',
	`canAccessConfiguration` enum('true','false') NOT NULL DEFAULT 'false',
	`canManagePermissions` enum('true','false') NOT NULL DEFAULT 'false',
	`canViewAuditLogs` enum('true','false') NOT NULL DEFAULT 'false',
	`canExportData` enum('true','false') NOT NULL DEFAULT 'false',
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rolePermissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `rolePermissions_role_unique` UNIQUE(`role`)
);
